### ISSUE TITLE
change font style?

### ISSUE THREAD

**Issue by danass** [Citytracking/toner#78]
Hello,
Is it possible to change font style and size from toner.
Im using Maperitive, and it seems the rules are not effective unless using layers.
I wish i could just modify the size and the font of the actual toner.

**Comment by almccon** [comment]
Hi @danass. No, you can't change the font size or style on Toner. The tiles are pre-rendered with one style of font. If you wanted to generate your own tiles using a modified version of the Toner style, that is possible, but it is difficult, and it would require installing a lot more software than just using Maperitive.

Also, this repo is for an older version of Toner, the repo for the new version is hosted here: http://github.com/stamen/toner-carto
