### ISSUE TITLE
Be able to choose detail level

### ISSUE THREAD

**Issue by chanibal** [Citytracking/toner#79]
When I select some area on a map, I would like to keep the level of detail that is rendered on screen. But when I click the make button, the amount of streets is much much higher. While this may be better for most uses, sometimes someone needs a less detailed map.

**Comment by almccon** [comment]
Hi! We're not supporting this repo anymore... Toner has moved to https://github.com/stamen/toner-carto, but I think you're talking about the `<image>` button on maps.stamen.com, which is better discussed here: https://github.com/stamen/maps.stamen.com/issues

Will you create an issue over there, please?
