### ISSUE TITLE
Vector or high res output?

### ISSUE THREAD

**Issue by chanibal** [Citytracking/toner#80]
It would be great if toner could output maps in svg or as a higher resolution png.

**Comment by almccon** [comment]
Hi! We're not supporting this repo anymore... Toner has moved to https://github.com/stamen/toner-carto. Unfortunately, it's not possible to export toner as SVG, although you could create a higher resolution png by stitching together enough screenshots to cover the area you want. I know it's not quite elegant, but it works. Hopefully that will be good enough for your needs.
